-- Audit event log table
-- Append-only; no status column, no AbstractAuditingEntity columns.
-- PK is BIGINT generated by TSID (io.hypersistence.utils) — no sequence DDL needed.
-- actor stores admin username (from SecurityUtil) or "client:{clientId}" for client-initiated events.
-- client_id is nullable — purely admin events without a client target may pass NULL.

CREATE TABLE main.audit_event (
    id           BIGINT       PRIMARY KEY,
    event_type   VARCHAR(50)  NOT NULL,
    client_id    BIGINT       REFERENCES main.client_account(id),
    actor        VARCHAR(100) NOT NULL,
    detail       TEXT,
    occurred_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_audit_event_client_occurred
    ON main.audit_event(client_id, occurred_at DESC)
    WHERE client_id IS NOT NULL;

CREATE INDEX idx_audit_event_occurred
    ON main.audit_event(occurred_at DESC);
