-- Phase 22: Segment deviation alert table
-- Records per-send-request billing deviations when actual segments differ from expected.
-- BOOK-01 through BOOK-06 and SEGDEV-01 through SEGDEV-04 requirements.
-- PK is BIGINT generated by TSID (io.hypersistence.utils) — no sequence DDL needed.

CREATE TABLE main.segment_deviation_alert (
    id                      BIGINT       PRIMARY KEY,
    send_request_id_fk      BIGINT       NOT NULL REFERENCES main.send_request(id),
    send_request_ref        VARCHAR(200) NOT NULL,
    client_id               BIGINT       NOT NULL,
    alert_type              VARCHAR(30)  NOT NULL,   -- SEGMENT | PLATFORM_FREEZE
    expected_total          BIGINT       NOT NULL,
    actual_total            BIGINT       NOT NULL,
    delta                   BIGINT       NOT NULL,
    shortfall_amount        BIGINT,                  -- null unless shortfall occurred (BOOK-05/06)
    client_frozen           BOOLEAN      NOT NULL DEFAULT FALSE,
    platform_frozen         BOOLEAN      NOT NULL DEFAULT FALSE,
    unrecovered_amount      BIGINT,                  -- null unless platform also ran dry (BOOK-06)
    per_recipient_breakdown JSONB        NOT NULL,
    financial_action        VARCHAR(30)  NOT NULL,   -- REFUNDED | EXTRA_DEBITED | SHORTFALL_ABSORBED
    status                  VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_by              VARCHAR(50),
    created_date            TIMESTAMPTZ,
    last_modified_by        VARCHAR(50),
    last_modified_date      TIMESTAMPTZ,
    request_id              VARCHAR(255),
    session_id              TEXT
);

CREATE INDEX idx_segment_deviation_alert_client_id
    ON main.segment_deviation_alert(client_id);

CREATE INDEX idx_segment_deviation_alert_send_request_id_fk
    ON main.segment_deviation_alert(send_request_id_fk);

CREATE INDEX idx_segment_deviation_alert_alert_type
    ON main.segment_deviation_alert(alert_type);
