-- Phase 23: Balance deviation alert table
-- Records periodic balance reconciliation mismatches between Nexah-reported
-- credits and Sendam-tracked platform balance.
-- PK is BIGINT generated by TSID (io.hypersistence.utils) — no sequence DDL needed.

CREATE TABLE main.balance_deviation_alert (
    id                  BIGINT       PRIMARY KEY,
    alert_type          VARCHAR(30)  NOT NULL DEFAULT 'BALANCE',
    nexah_balance       BIGINT       NOT NULL,
    sendam_balance      BIGINT       NOT NULL,
    delta               BIGINT       NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_by          VARCHAR(50),
    created_date        TIMESTAMPTZ,
    last_modified_by    VARCHAR(50),
    last_modified_date  TIMESTAMPTZ,
    request_id          VARCHAR(255),
    session_id          TEXT
);

CREATE INDEX idx_balance_deviation_alert_status
    ON main.balance_deviation_alert(status);

CREATE INDEX idx_balance_deviation_alert_created_date
    ON main.balance_deviation_alert(created_date);
