-- Phase 24: Deviation Alert Lifecycle
-- Adds alert_status to both alert tables (OPEN | ACKNOWLEDGED | RESOLVED).
-- Creates deviation_alert_event audit trail table for status transition history.
-- PKs use BIGINT generated by TSID (io.hypersistence.utils) — no sequence DDL needed.
-- Tables affected:
--   main.segment_deviation_alert  (Phase 22)
--   main.balance_deviation_alert  (Phase 23)
--   main.deviation_alert_event    (new — Phase 24)

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add alert_status to segment_deviation_alert
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE main.segment_deviation_alert
    ADD COLUMN alert_status VARCHAR(20) NOT NULL DEFAULT 'OPEN';

CREATE INDEX idx_segment_deviation_alert_alert_status
    ON main.segment_deviation_alert(alert_status);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Add alert_status to balance_deviation_alert
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE main.balance_deviation_alert
    ADD COLUMN alert_status VARCHAR(20) NOT NULL DEFAULT 'OPEN';

CREATE INDEX idx_balance_deviation_alert_alert_status
    ON main.balance_deviation_alert(alert_status);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Create deviation_alert_event audit trail table
--    Extends BaseEntity (owns acted_at/acted_by; no auditing columns).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE main.deviation_alert_event (
    id                  BIGINT       PRIMARY KEY,
    segment_alert_id_fk BIGINT       REFERENCES main.segment_deviation_alert(id),   -- null for BALANCE rows
    balance_alert_id_fk BIGINT       REFERENCES main.balance_deviation_alert(id),   -- null for SEGMENT/PLATFORM_FREEZE rows
    alert_type          VARCHAR(30)  NOT NULL,
    previous_status     VARCHAR(20)  NOT NULL,
    new_status          VARCHAR(20)  NOT NULL,
    admin_note          TEXT         NOT NULL,
    acted_by            VARCHAR(50)  NOT NULL,
    acted_at            TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_deviation_alert_event_segment_fk
    ON main.deviation_alert_event(segment_alert_id_fk);

CREATE INDEX idx_deviation_alert_event_balance_fk
    ON main.deviation_alert_event(balance_alert_id_fk);
