-- Webhook infrastructure tables
-- PKs are BIGINT generated by TSID (io.hypersistence.utils) — no sequence DDL needed.
-- Follows the same column conventions as send_request (V5), with inherited AbstractAuditingEntity
-- columns: created_by, created_date, last_modified_by, last_modified_date, request_id, session_id, status.
-- The inherited `status` column carries EntityStatus (ACTIVE/INACTIVE/DELETED) for entity lifecycle.
-- Webhook-specific lifecycle state uses separate named columns to avoid collisions.

CREATE TABLE main.webhook_endpoint (
    id                  BIGINT PRIMARY KEY,
    client_id           BIGINT NOT NULL REFERENCES main.client_account(id),
    public_id           VARCHAR(30) NOT NULL UNIQUE,
    url                 VARCHAR(2048) NOT NULL,
    events              VARCHAR(100) NOT NULL DEFAULT 'sms.finalized',
    -- inherited AbstractAuditingEntity columns
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by          VARCHAR(50),
    created_date        TIMESTAMP,
    last_modified_by    VARCHAR(50),
    last_modified_date  TIMESTAMP,
    request_id          VARCHAR(100),
    session_id          TEXT,
    CONSTRAINT uq_webhook_endpoint_client UNIQUE (client_id)
);

CREATE TABLE main.webhook_delivery (
    id                      BIGINT PRIMARY KEY,
    webhook_endpoint_id     BIGINT NOT NULL REFERENCES main.webhook_endpoint(id),
    client_id               BIGINT NOT NULL REFERENCES main.client_account(id),
    send_request_id         VARCHAR(200) NOT NULL,
    recipient               VARCHAR(20) NOT NULL,
    gateway_message_id      VARCHAR(100),
    -- semantic delivery outcome stored by listener (DELIVERED / FAILED)
    delivery_status         VARCHAR(20) NOT NULL,
    payload                 TEXT NOT NULL,
    -- webhook attempt lifecycle: PENDING, DELIVERED, FAILED, EXHAUSTED
    attempt_status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count           INT NOT NULL DEFAULT 0,
    next_attempt_at         TIMESTAMP NOT NULL,
    last_attempt_at         TIMESTAMP,
    http_status             INT,
    -- inherited AbstractAuditingEntity columns
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by              VARCHAR(50),
    created_date            TIMESTAMP,
    last_modified_by        VARCHAR(50),
    last_modified_date      TIMESTAMP,
    request_id              VARCHAR(100),
    session_id              TEXT
);

CREATE INDEX idx_webhook_delivery_due
    ON main.webhook_delivery(attempt_status, next_attempt_at)
    WHERE attempt_status = 'PENDING';
